In [2]:
import numpy as np

In [12]:
arr1 = np.random.randint(1,51, size=(5,5))
print(arr1)
print()



[[22 30  5 48 49]
 [21  4  2 25 47]
 [ 7  8 25 30 32]
 [39 22 36 35 18]
 [10 26 30 38 29]]



In [15]:
print("second row", arr1[1,:])
print()
print("third column", arr1[:,2])
print()
print(arr1[:3,:3])
print()
print(arr1[arr1>30])

second row [21  4  2 25 47]

third column [ 5  2 25 36 30]

[[22 30  5]
 [21  4  2]
 [ 7  8 25]]

[48 49 47 32 39 36 35 38]


In [17]:
arr2 = np.arange(1,21)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [20]:
even_num = arr2[arr2%2==0]
print("even numbers:", even_num)
print()
arr2[arr2%3==0]= -1
print(arr2)
print()
arr2_new = np.arange(1,21)
gtt_arr2 = arr2_new[arr2_new>10]
print("greater than 10:", gtt_arr2)
print()


even numbers: [ 2  4  8 10 14 16 20]

[ 1  2 -1  4  5 -1  7  8 -1 10 11 -1 13 14 -1 16 17 -1 19 20]

greater than 10: [11 12 13 14 15 16 17 18 19 20]

