In [2]:
import numpy as np

In [12]:
arr1 = np.random.randint(1,51, size=(5,5))
print(arr1)
print()



[[22 30  5 48 49]
 [21  4  2 25 47]
 [ 7  8 25 30 32]
 [39 22 36 35 18]
 [10 26 30 38 29]]



In [15]:
print("second row", arr1[1,:])
print()
print("third column", arr1[:,2])
print()
print(arr1[:3,:3])
print()
print(arr1[arr1>30])

second row [21  4  2 25 47]

third column [ 5  2 25 36 30]

[[22 30  5]
 [21  4  2]
 [ 7  8 25]]

[48 49 47 32 39 36 35 38]


In [17]:
arr2 = np.arange(1,21)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [20]:
even_num = arr2[arr2%2==0]
print("even numbers:", even_num)
print()
arr2[arr2%3==0]= -1
print(arr2)
print()
arr2_new = np.arange(1,21)
gtt_arr2 = arr2_new[arr2_new>10]
print("greater than 10:", gtt_arr2)
print()


even numbers: [ 2  4  8 10 14 16 20]

[ 1  2 -1  4  5 -1  7  8 -1 10 11 -1 13 14 -1 16 17 -1 19 20]

greater than 10: [11 12 13 14 15 16 17 18 19 20]



In [35]:
arr3 = np.arange(16)
print(arr3)
print()
re_arr3 = arr3.reshape(4,4)
print(re_arr3)
tr_arr3 = re_arr3.T
print()
print(tr_arr3)

flt_arr3 = tr_arr3.flatten()
print()
print(flt_arr3)
print()
print(re_arr3.flatten())
print()
print(re_arr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]

[ 0  4  8 12  1  5  9 13  2  6 10 14  3  7 11 15]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [46]:
arr4 = np.random.randint(1,10,size=(3,3))
arr4_2 = np.arange(1,4)
print(arr4)
print()
print(arr4_2,"\n")

print("addition:\n", arr4 + arr4_2)
print()
print("subtraction:\n", arr4 - arr4_2)
print()
print("multiplication:\n", arr4 * arr4_2)
print()

[[7 9 5]
 [8 2 8]
 [7 9 6]]

[1 2 3] 

addition:
 [[ 8 11  8]
 [ 9  4 11]
 [ 8 11  9]]

subtraction:
 [[6 7 2]
 [7 0 5]
 [6 7 3]]

multiplication:
 [[ 7 18 15]
 [ 8  4 24]
 [ 7 18 18]]



In [47]:
mat1 = np.random.randint(1,10,size=(3,3))
mat2 = np.random.randint(1,10,size=(3,3))

print("matrix 1:\n", mat1)
print()
print("matrix 2:\n", mat2)
print()

matrix 1:
 [[2 7 9]
 [6 8 9]
 [4 7 4]]

matrix 2:
 [[4 2 4]
 [4 4 1]
 [7 1 5]]



In [56]:
print(mat1 @ mat2)
print()
print(np.dot(mat1, mat2))
print()
print(mat1.dot(mat2))
print()
print("element-wise multiplication:\n", mat1 * mat2)
print()
det = np.linalg.det(mat1)
print(f"determinant of matrix 1: {det:.2f}")
print()
eigvals, eigvecs = np.linalg.eig(mat1)
print("eigenvalues of matrix 1:", eigvals)
print()
print("eigenvectors of matrix 1:\n", eigvecs)


[[ 99  41  60]
 [119  53  77]
 [ 72  40  43]]

[[ 99  41  60]
 [119  53  77]
 [ 72  40  43]]

[[ 99  41  60]
 [119  53  77]
 [ 72  40  43]]

element-wise multiplication:
 [[ 8 14 36]
 [24 32  9]
 [28  7 20]]

determinant of matrix 1: 112.00

eigenvalues of matrix 1: [18.8299606+0.j         -2.4149803+0.34034979j -2.4149803-0.34034979j]

eigenvectors of matrix 1:
 [[-0.54204261+0.j         -0.88892889+0.j         -0.88892889-0.j        ]
 [-0.69404593+0.j          0.39978443+0.12843802j  0.39978443-0.12843802j]
 [-0.47380382+0.j          0.12512362-0.13351255j  0.12512362+0.13351255j]]


In [66]:
arr6 = np.random.rand(5,4)

print(arr6,"\n")


[[0.81333889 0.31219316 0.6501554  0.54020046]
 [0.79006895 0.3044851  0.5036858  0.54213419]
 [0.62313925 0.16786931 0.5788646  0.08933561]
 [0.46227241 0.90898062 0.40637768 0.56850837]
 [0.9104491  0.88275333 0.21684456 0.04162121]] 



In [77]:
print(f"Mean: {np.mean(arr6):.2f} , Median: {np.median(arr6):.2f} , std: {np.std(arr6):.2f} \n")

print("Max per column:", np.max(arr6, axis=0))
print("Min per row:", np.min(arr6, axis=1))
print()
print(np.max(arr6))
print(np.min(arr6))
print(arr6.min(axis=0))

print()
# 3. Normalize (Min-Max Scaling)
# Formula: (x - min) / (max - min)
norm_arr6 = (arr6 - arr6.min()) / (arr6.max() - arr6.min())
print("Normalized array:\n", norm_arr6)



Mean: 0.52 , Median: 0.54 , std: 0.26 

Max per column: [0.9104491  0.90898062 0.6501554  0.56850837]
Min per row: [0.31219316 0.3044851  0.08933561 0.40637768 0.04162121]

0.9104491031427419
0.041621214649094074
[0.46227241 0.16786931 0.21684456 0.04162121]

Normalized array:
 [[0.88822848 0.3114218  0.70040821 0.57385272]
 [0.86144534 0.30255001 0.53182523 0.5760784 ]
 [0.66931327 0.14530852 0.61835421 0.05491812]
 [0.4841594  0.99830982 0.41982592 0.60643444]
 [1.         0.96812283 0.20167785 0.        ]]


In [80]:
arr7 = np.random.randint(1,100, size=(10))
print("Original array:", arr7)

Original array: [24 94 85 18 11  6 86 61 15 81]


In [95]:
#sort
print("Sorted array:", np.sort(arr7))

# Indices of sorted array
sorted_indices = np.argsort(arr7)
print("Indices of sorted array:", sorted_indices)

#search
min_id = np.argmin(arr7)
print("Index of minimum value:", min_id)

#search using where
gt_50_indices = np.where(arr7 > 50)
print("Indices of elements greater than 50:", gt_50_indices[0])
max_id = np.where(arr7 == np.max(arr7))
print("Index of maximum value:", max_id)
max_id = np.argmax(arr7)
print("Index of maximum value using argmax:", max_id)

Sorted array: [ 6 11 15 18 24 61 81 85 86 94]
Indices of sorted array: [5 4 8 3 0 7 9 2 6 1]
Index of minimum value: 5
Indices of elements greater than 50: [1 2 6 7 9]
Index of maximum value: (array([1]),)
Index of maximum value using argmax: 1


In [106]:
arr8 = np.arange(1,37).reshape(6,6)
print("Original 6x6 array:\n", arr8)
print()
#alternate rows
print(arr8[::2,:],"\n")

#alternate columns
print(arr8[:,::2],"\n")

#main diagonal
print("Main diagonal:", np.diag(arr8),"\n")
#secondary diagonal
print("Secondary diagonal:", np.diag(np.fliplr(arr8)), "\n")

#diagonal without function
print("Diagonal: " , arr8[np.arange(6), np.arange(6)])



Original 6x6 array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

[[ 1  2  3  4  5  6]
 [13 14 15 16 17 18]
 [25 26 27 28 29 30]] 

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]
 [19 21 23]
 [25 27 29]
 [31 33 35]] 

Main diagonal: [ 1  8 15 22 29 36] 

Secondary diagonal: [ 6 11 16 21 26 31] 

Diagonal:  [ 1  8 15 22 29 36]


In [115]:
base = np.random.randint(1, 10, (4, 4))
print("Original array:\n", base)
print()

# 1. Add row of zeros
row_zeros = np.zeros((1, 4)) # Shape must match columns
base = np.vstack([base, row_zeros])

print("After adding row of zeros:\n", base)
print()

# 2. Add column of ones
col_ones = np.ones((5, 1)) # Shape must match new row count (5)
base = np.hstack([base, col_ones])
print("After adding column of ones:\n", base)
print()

# 3. Delete 2nd row (index 1) and 3rd column (index 2)
# Note: Axis 0 is rows, Axis 1 is cols
base = np.delete(base, 1, axis=0) # Delete row
base = np.delete(base, 2, axis=1) # Delete col
print("Final Shape:", base.shape)
print("Array after deletions:\n", base)

Original array:
 [[1 9 9 1]
 [3 4 6 3]
 [1 2 5 9]
 [1 8 2 9]]

After adding row of zeros:
 [[1. 9. 9. 1.]
 [3. 4. 6. 3.]
 [1. 2. 5. 9.]
 [1. 8. 2. 9.]
 [0. 0. 0. 0.]]

After adding column of ones:
 [[1. 9. 9. 1. 1.]
 [3. 4. 6. 3. 1.]
 [1. 2. 5. 9. 1.]
 [1. 8. 2. 9. 1.]
 [0. 0. 0. 0. 1.]]

Final Shape: (4, 4)
Array after deletions:
 [[1. 9. 1. 1.]
 [1. 2. 9. 1.]
 [1. 8. 9. 1.]
 [0. 0. 0. 1.]]


In [118]:
# Coefficients Matrix A
A = np.array([
    [2, 1, -1],
    [-3, -1, 2],
    [-2, 1, 2]
])

# Constants Vector B
B = np.array([8, -11, -3])

# Solve
solution = np.linalg.solve(A, B)
print(f"Solution: x={solution[0]:.2f}, y={solution[1]:.2f}, z={solution[2]:.2f}")

# Verify: A dot X should equal B
print("Check (Ax - B):", np.allclose(np.dot(A, solution), B))
print(np.dot(A, solution), "==" , B)

Solution: x=2.00, y=3.00, z=-1.00
Check (Ax - B): True
[  8. -11.  -3.] == [  8 -11  -3]
